services:

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - 3306:3306

  backend:
    build: ./backend/
    ports:
      - 8080:8080
    environment:
      MYSQL_DB_HOST: db
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: 1234
    depends_on:
      - db

  frontend:
    build: ./frontend/
    ports:
      - 80:80
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080