apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-planner-adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel-planner-adminer
      tier: admin
  template:
    metadata:
      labels:
        app: travel-planner-adminer
        tier: admin
    spec:
      containers:
      - name: travel-planner-adminer
        image: adminer
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: travel-planner-zendebudi-adminer
  name: travel-planner-adminer-service
spec:
  type: LoadBalancer
  selector:
    app: travel-planner-adminer
    tier: admin
  ports:
  - port: 80
    targetPort: 8080
