# SHOULD BE IGNORED BY GIT - INDEXED HERE FOR DEMONSTRATION PURPOSES

apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  mysql-username: akZDc0BVR2g3cHVxZkRQeHBYUXRxXnJnYVpLYyVXajNH
  mysql-password: R3Mhd1lENnNpQktwdnl1RnMzU1M1TUBwNmIhIVVi
