apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-standard-zrs
provisioner: disk.csi.azure.com
parameters:
  skuName: Standard_ZRS
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-standard-zrs
  resources:
    requests:
      storage: 1Gi